services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: postgresdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
    container_name: backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://dbuser:dbpassword@db:5432/postgresdb
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:

